# Generated by Django 5.1.1 on 2024-10-09 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='', max_length=255)),
                ('instagram', models.CharField(default='', max_length=255)),
                ('tiktok', models.CharField(default='', max_length=255)),
                ('linkedin', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('example', 'Assignment'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('module', 'Module')], max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('is_admin', models.BooleanField(default=False)),
                ('bio', models.CharField(default='', max_length=255)),
                ('is_banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('socials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.accountsocials')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('question', models.CharField(default='', max_length=1023)),
                ('image', models.FileField(blank=True, null=True, upload_to='elem_assignment/')),
                ('answers', models.JSONField()),
                ('correct_answer_indices', models.JSONField()),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('explanation', models.CharField(default='', max_length=4095)),
            ],
            bases=('api.element',),
        ),
        migrations.CreateModel(
            name='ExamElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('description', models.CharField(default='', max_length=1023)),
                ('duration', models.IntegerField(default=3600)),
                ('total_marks', models.IntegerField(default=1)),
            ],
            bases=('api.element',),
        ),
        migrations.CreateModel(
            name='ExampleElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('question', models.CharField(default='', max_length=1023)),
                ('image', models.FileField(blank=True, null=True, upload_to='elem_example/')),
                ('explanation', models.CharField(default='', max_length=4095)),
            ],
            bases=('api.element',),
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('image', models.FileField(blank=True, null=True, upload_to='elem_img/')),
                ('description', models.CharField(default='', max_length=1023)),
            ],
            bases=('api.element',),
        ),
        migrations.CreateModel(
            name='ModuleElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('description', models.CharField(default='', max_length=1023)),
                ('image', models.FileField(blank=True, null=True, upload_to='elem_module/')),
            ],
            bases=('api.element',),
        ),
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('content', models.CharField(default='', max_length=4095)),
            ],
            bases=('api.element',),
        ),
        migrations.CreateModel(
            name='VideoElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.element')),
                ('video', models.FileField(blank=True, null=True, upload_to='elem_vid/')),
                ('description', models.CharField(default='', max_length=1023)),
            ],
            bases=('api.element',),
        ),
        migrations.AddField(
            model_name='element',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnammed Course', max_length=255)),
                ('description', models.CharField(default='No description provided.', max_length=4095)),
                ('image', models.FileField(blank=True, null=True, upload_to='courses_imgs/')),
                ('language', models.CharField(default='EN', max_length=31)),
                ('duration', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('price_currency', models.CharField(default='PLN', max_length=7)),
                ('price', models.IntegerField(default=0)),
                ('promo_price', models.IntegerField(default=0)),
                ('promo_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.CharField(default='', max_length=1023)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignmentelement')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examelement')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleToElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_modules', to='api.element')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_elements', to='api.moduleelement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduleelement')),
            ],
        ),
    ]
