# Generated by Django 5.1.1 on 2024-10-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
