# Generated by Django 5.1.1 on 2024-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coursemodule_options_coursemodule_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='examquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
