# Generated by Django 5.1.1 on 2024-10-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_examquestion_options_examquestion_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='title',
            new_name='name',
        ),
    ]
