# Generated by Django 5.1.1 on 2024-10-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='billing_period',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_end',
        ),
    ]
