# Generated by Django 5.1.1 on 2024-10-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_subscription_billing_period_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='CourseAccess',
        ),
    ]
