# Generated by Django 5.1.1 on 2024-10-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_access_expires_on_courseaccess_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentelement',
            name='explanation_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='elem_assignment/'),
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=127)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignmentelement')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursetopic')),
            ],
        ),
    ]
