# Generated by Django 5.1.1 on 2024-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_assignmentelement_explanation_image_coursetopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='en', max_length=31),
        ),
    ]
