# Generated by Django 5.1.1 on 2024-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_currency',
            field=models.CharField(default='USD', max_length=7),
        ),
    ]
