# Generated by Django 5.1.1 on 2024-10-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_course_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduleelement')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursetopic')),
            ],
        ),
    ]
