# Generated by Django 5.1.1 on 2024-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_moduleweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleelement',
            name='explanation_image',
            field=models.FileField(blank=True, null=True, upload_to='elem_example/'),
        ),
    ]
