# Generated by Django 5.1.1 on 2024-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_exampleelement_explanation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
