# Generated by Django 5.1.1 on 2024-11-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_examquestion_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletoelement',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='element_to_module_course', to='api.course'),
        ),
    ]
