# Generated by Django 5.1.1 on 2024-11-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_moduletoelement_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('course_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursetopic')),
            ],
        ),
    ]
