# Generated by Django 5.1.1 on 2024-11-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_accounttopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleToElement',
            new_name='ElementToModule',
        ),
        migrations.RenameModel(
            old_name='CourseModule',
            new_name='ModuleToCourse',
        ),
    ]
