# Generated by Django 5.1.1 on 2024-11-23 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_moduletoelement_elementtomodule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accounttopic',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_topics', to='api.account'),
        ),
        migrations.AlterField(
            model_name='accounttopic',
            name='course_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_topics', to='api.coursetopic'),
        ),
        migrations.AlterField(
            model_name='assignmentweight',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_weights', to='api.assignmentelement'),
        ),
        migrations.AlterField(
            model_name='assignmentweight',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_weights', to='api.coursetopic'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.account'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to='api.account'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to='api.course'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.course'),
        ),
        migrations.AlterField(
            model_name='element',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.account'),
        ),
        migrations.AlterField(
            model_name='elementtomodule',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.element'),
        ),
        migrations.AlterField(
            model_name='elementtomodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.moduleelement'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.examelement'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='api.assignmentelement'),
        ),
        migrations.AlterField(
            model_name='moduletocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course'),
        ),
        migrations.AlterField(
            model_name='moduletocourse',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.moduleelement'),
        ),
        migrations.AlterField(
            model_name='moduleweight',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_weights', to='api.moduleelement'),
        ),
        migrations.AlterField(
            model_name='moduleweight',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_weights', to='api.coursetopic'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.account'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.course'),
        ),
    ]
