# Generated by Django 5.1.1 on 2024-11-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_moduletocourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='api.course'),
        ),
        migrations.AlterField(
            model_name='moduletocourse',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.moduleelement'),
        ),
    ]
