# Generated by Django 5.1.1 on 2024-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_moduletocourse_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementtomodule',
            name='course',
        ),
        migrations.AddField(
            model_name='assignmentelement',
            name='hide_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ModuleWeight',
        ),
    ]
