# Generated by Django 5.1.1 on 2024-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_elementtomodule_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentelement',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assignmentelement',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='examelement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='examelement',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exampleelement',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exampleelement',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='moduleelement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
