# Generated by Django 5.1.1 on 2024-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_assignmentelement_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaccess',
            name='is_gifted',
            field=models.BooleanField(default=False),
        ),
    ]
