# Generated by Django 5.1.1 on 2024-12-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_courseaccess_is_gifted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseaccess',
            name='is_gifted',
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='obtaining_type',
            field=models.CharField(choices=[('author', 'Author'), ('gifted', 'Gifted'), ('bought', 'Bought')], default='bought', max_length=16),
        ),
    ]
