# Generated by Django 5.1.1 on 2024-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_courseaccess_is_gifted_courseaccess_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaccess',
            name='obtaining_type',
            field=models.CharField(choices=[('author', 'Author'), ('gifted', 'Gifted'), ('bought', 'Bought'), ('free', 'Free')], default='bought', max_length=16),
        ),
    ]
