# Generated by Django 5.1.1 on 2025-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_courseaccess_obtaining_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaccess',
            name='obtaining_type',
            field=models.CharField(choices=[('author', 'Author'), ('gifted', 'Gifted'), ('bought', 'Bought')], default='bought', max_length=16),
        ),
    ]
